
# List available commands
default:
  just --list

# Start dev server
dev:
  npm run dev

# Build the website
build:
  npm run build

# Deploy the website
deploy:
  rsync --archive dist/ root@shimmermathlabs.com:/var/www/shimmermathlabs/
